### ISSUE TITLE
v2.1.1 problem to connect with Hadoop

### ISSUE THREAD

**Issue by viniciosbarretos** [SIDN/entrada#123]
Hello!

Today, I updated ENTRADA container from v2.0.19 to v2.1.1 and now it is not connecting with hadoop properly.

When the container starts, this error appears:
```
entrada_1  | 2020-04-14 20:17:19.495  WARN 6 --- [           main] org.apache.hadoop.util.NativeCodeLoader  : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
entrada_1  | log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
entrada_1  | log4j:WARN Please initialize the log4j system properly.
entrada_1  | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
entrada_1  | 2020-04-14 20:17:50.230 ERROR 6 --- [           main] n.s.entrada.engine.AbstractQueryEngine   : SQL execution failed, sql: CREATE DATABASE IF NOT EXISTS entrada
entrada_1  |   COMMENT 'ENTRADA database'
entrada_1  |   LOCATION 'hdfs://hdfs1:8020/user/entrada/database'
entrada_1  | 
entrada_1  | org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: [Cloudera][ImpalaJDBCDriver](700100) Connection timeout expired. Details: None.
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:370) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:417) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at nl.sidnlabs.entrada.engine.AbstractQueryEngine.execute(AbstractQueryEngine.java:60) ~[classes!/:2.1.1]
entrada_1  | 	at nl.sidnlabs.entrada.initialize.AbstractInitializer.initializeDatabase(AbstractInitializer.java:113) [classes!/:2.1.1]
entrada_1  | 	at nl.sidnlabs.entrada.initialize.AbstractInitializer.init(AbstractInitializer.java:75) [classes!/:2.1.1]
entrada_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]
entrada_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]
entrada_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
entrada_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
entrada_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
entrada_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
entrada_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
entrada_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
entrada_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
entrada_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
entrada_1  | 	at nl.sidnlabs.entrada.Application.main(Application.java:40) ~[classes!/:2.1.1]
entrada_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]
entrada_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]
entrada_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
entrada_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
entrada_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) ~[entrada.jar:2.1.1]
entrada_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) ~[entrada.jar:2.1.1]
entrada_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[entrada.jar:2.1.1]
entrada_1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[entrada.jar:2.1.1]
entrada_1  | Caused by: java.sql.SQLException: [Cloudera][ImpalaJDBCDriver](700100) Connection timeout expired. Details: None.
entrada_1  | 	at com.cloudera.impala.jdbc.core.LoginTimeoutConnection.handleException(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.hivecommon.core.HiveJDBCCommonConnection.handleException(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.core.LoginTimeoutConnection.connect(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.common.AbstractDataSource.getSimbaConnection(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.common.AbstractDataSource.getConnection(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	... 38 common frames omitted
entrada_1  | Caused by: com.cloudera.impala.support.exceptions.ErrorException: [Cloudera][ImpalaJDBCDriver](700100) Connection timeout expired. Details: None.
entrada_1  | 	... 47 common frames omitted
entrada_1  | 
```

After process any pcap file, it stucks with this error:

```
entrada_1  | 2020-04-14 15:22:19.855  INFO 6 --- [taskScheduler-3] n.s.entrada.engine.AbstractQueryEngine   : Add partition: Partition(dns=true, year=2020, month=4, day=14, server=nameserver.example.issue) to table: dns
entrada_1  | 2020-04-14 15:22:19.856  INFO 6 --- [taskScheduler-3] n.s.entrada.engine.AbstractQueryEngine   : Create partition, sql: ALTER TABLE entrada.dns ADD IF NOT EXISTS PARTITION (year=2020,month=4,day=14,server='nameserver.example.issue');
entrada_1  | 
entrada_1  | 2020-04-14 15:22:49.860 ERROR 6 --- [taskScheduler-3] n.s.entrada.engine.AbstractQueryEngine   : SQL execution failed, sql: ALTER TABLE entrada.dns ADD IF NOT EXISTS PARTITION (year=2020,month=4,day=14,server='nameserver.example.issue');
entrada_1  | 
entrada_1  | 
entrada_1  | org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: [Cloudera][ImpalaJDBCDriver](700100) Connection timeout expired. Details: None.
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:370) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:417) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at nl.sidnlabs.entrada.engine.AbstractQueryEngine.execute(AbstractQueryEngine.java:60) [classes!/:2.1.1]
entrada_1  | 	at nl.sidnlabs.entrada.engine.AbstractQueryEngine.addPartition(AbstractQueryEngine.java:218) [classes!/:2.1.1]
entrada_1  | 	at nl.sidnlabs.entrada.service.UploadService.upload(UploadService.java:69) [classes!/:2.1.1]
entrada_1  | 	at nl.sidnlabs.entrada.load.PacketProcessor.execute(PacketProcessor.java:218) [classes!/:2.1.1]
entrada_1  | 	at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160) ~[micrometer-core-1.2.0.jar!/:1.2.0]
entrada_1  | 	at nl.sidnlabs.entrada.ScheduledExecution.runForServer(ScheduledExecution.java:94) ~[classes!/:2.1.1]
entrada_1  | 	at nl.sidnlabs.entrada.ScheduledExecution.lambda$run$0(ScheduledExecution.java:71) ~[classes!/:2.1.1]
entrada_1  | 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_242]
entrada_1  | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[na:1.8.0_242]
entrada_1  | 	at nl.sidnlabs.entrada.ScheduledExecution.run(ScheduledExecution.java:71) ~[classes!/:2.1.1]
entrada_1  | 	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[na:na]
entrada_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
entrada_1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
entrada_1  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_242]
entrada_1  | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_242]
entrada_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_242]
entrada_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_242]
entrada_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
entrada_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
entrada_1  | 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
entrada_1  | Caused by: java.sql.SQLException: [Cloudera][ImpalaJDBCDriver](700100) Connection timeout expired. Details: None.
entrada_1  | 	at com.cloudera.impala.jdbc.core.LoginTimeoutConnection.handleException(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.hivecommon.core.HiveJDBCCommonConnection.handleException(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.core.LoginTimeoutConnection.connect(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.common.AbstractDataSource.getSimbaConnection(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at com.cloudera.impala.jdbc.common.AbstractDataSource.getConnection(Unknown Source) ~[ImpalaJDBC41-2.6.4.jar!/:na]
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) ~[spring-jdbc-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
entrada_1  | 	... 24 common frames omitted
entrada_1  | Caused by: com.cloudera.impala.support.exceptions.ErrorException: [Cloudera][ImpalaJDBCDriver](700100) Connection timeout expired. Details: None.
entrada_1  | 	... 33 common frames omitted
entrada_1  | 
```

I made the rollback to version 2.0.19 for a while. Everything working properly.

Thanks

**Comment by mwullink** [comment]
Hi Vinicios,

It looks like ENTRADA has a problem connection to the Hadoop cluster, are you sure you have the following environment variables correctly set in your docker-compose.yml?

   - HDFS_NAMESERVICE_HOST=
   - IMPALA_DAEMON_HOST=nameservice
    - ENTRADA_LOCATION_OUTPUT=hdfs://nameservice/user/entrada/database
    - HDFS_USERNAME=hdfs

     # The following options do NOT need to be changed
     # change the volume mappings below, in the "volumes:" section
    - ENTRADA_ENGINE=hadoop
      # If Kerberos is used provide credentials
      # AND place a keytab, krb5.conf and JAAS config files in the conf directory
      # make sure the keytab path in the JAAS config file uses internal container path: /entrada/data/conf
   - KERBEROS_REALM=
   - KERBEROS_KEYTAB=
   - IMPALA_SSL=1
- |
        JAVA_OPTS=
        -Djava.security.krb5.conf=/entrada/data/conf/krb5.conf
        -Djava.security.auth.login.config=/entrada/data/conf/jaas.conf


Maybe you created a new homidr for entrada and forgot to include the hadoop conf files?
Are the Hadoop config files ( core-site.xml and hdfs-site.xml) available in the conf dir?
if Kerberos is used provide credentials, place a keytab, krb5.conf and JAAS config files in the conf directory

Let me know if this helps.

Best,

Maarten

--
Maarten Wullink | Research Engineer
SIDN | Meander 501 | 6825 MD | Postbus 5022 | 6802 EA | ARNHEM
T +31 (0)26 352 55 45 | M +31 (0)6 21 26 87 55
maarten.wullink@sidn.nl | www.sidn.nl
pgp key: http://pgp.mit.edu/pks/lookup?op=get&search=0x4F2A495C4B1BF08B

**Comment by viniciosbarretos** [comment]
Hello, Maarten! Thanks for the fast support.

I'm not using Kerberos.

I've used exactly the same docker-compose and conf files. When I updated version, the only thing I changed is the docker compose file, changing `image: sidnlabs/entrada:2.0.19` to `image: sidnlabs/entrada:2.1.1`. The directory is the same.

This is my compose file:

```
version: '3.7'
services:
  entrada:
    image: sidnlabs/entrada:2.0.19
    restart: always
    ports:
      - 8080:8080
    environment:
      # ENTRADA options
      - ENTRADA_NAMESERVERS=<hidden>
      - ENTRADA_EXECUTION_DELAY=10
      - ENTRADA_PARQUET_COMPACTION_INTERVAL=60

      # Maxmind Database Free License 
      - GEOIP_MAXMIND_LICENSE_FREE=<hidden>
     
      # PostgreSQL config options, make sure the the database is created before
      # starting the container
      # replace <host_or_ip> with the actual host of ip, do not use localhost
      - SPRING_DATASOURCE_URL=jdbc:postgresql://<hidden>:5432/entrada
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=entrada
      - SPRING_DATASOURCE_PASSWORD=<hidden>
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      # Hadoop ( copy core-site.xml and hdfs-site.xml to the conf dir)
      - HDFS_NAMESERVICE_HOST=hdfs1
      - IMPALA_DAEMON_HOST=hdfs3
      - ENTRADA_LOCATION_OUTPUT=hdfs://hdfs1:8020/user/entrada/database
      - HDFS_USERNAME=hdfs
      
      # The following options do NOT need to be changed
      # change the volume mappings below, in the "volumes:" section
      - ENTRADA_ENGINE=hadoop
      - JAVA_OPTS=-Xmx4g -Xms4g

      # Metrics Graphite
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_ENABLED=true
      - MANAGEMENT_METRICS_EXPORT_GRAPHITE_HOST=localhost

      # Map internal container path to a path on the host
      # format <host-path>:<container:path>
      # ENTRADA will write to /entrada/... in the container
    volumes:
      - ./:/entrada/data/
    dns:
      - <hidden>
    #Limit container logging
    logging:
      options:
        max-size: "10m"
        max-file: "3"

    network_mode: host
```

When I use compose with `image: sidnlabs/entrada:2.0.19` everything works right. Erros only appears when I change the compose to v2.1.1

Sincerely,

Vinicios

**Comment by mwullink** [comment]
Hi,

Are you using HDFS High Availability?
see: https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithNFS.html

Can you try something for me?

In the Cloudera Hadoop conf file hdfs-site.xml is a property called “dfs.nameservices” its value is comma separated list of names.
Use 1 of those names for the docker-compose variable HDFS_NAMESERVICE_HOST.

for example, if this is your hdfs-site.xml :

  <property>
    <name>dfs.nameservices</name>
    <value>nameservice</value>
  </property>


The use this in docker-compose:

- HDFS_NAMESERVICE_HOST=nameservice


Let me know if this helps.

Best,

Maarten


--
Maarten Wullink | Research Engineer
SIDN | Meander 501 | 6825 MD | Postbus 5022 | 6802 EA | ARNHEM
T +31 (0)26 352 55 45 | M +31 (0)6 21 26 87 55
maarten.wullink@sidn.nl | www.sidn.nl
pgp key: http://pgp.mit.edu/pks/lookup?op=get&search=0x4F2A495C4B1BF08B

**Comment by viniciosbarretos** [comment]
Hi Maarten!

The timeout that occurs when ENTRADA try to connect with HDFS is caused by a change at `src/main/resources/application.properties` file in v2.0.21. Previous versions used `impala.ssl=0`, and after v2.0.21 it has changed to `impala.ssl=1`, causing issues for who aren't using SSL. You can see that [here](https://github.com/SIDN/entrada/compare/2.0.20...2.0.21).

Now, about the connection timeout when run SQL ALTER TABLE, after I activate HDFS High Availability, changed SSL settings and follow steps described in your last comment, everything worked perfectly. The only thing I had to do is change ENTRADA_LOCATION_OUTPUT address, putting nameservice instead hdfs hostname.

I made a pull request changing impala.ssl back to 0 original value. Maybe someone can have trouble with this. If you think it is trivial, I suggest to change default value in [ENTRADA Website](https://entrada.sidnlabs.nl/about/configuration/#hadoop).

Thanks for your help, ENTRADA have been a very good tool for us at Brasil. I'm in my last year of Bachelor of Computer Science and I'll cite ENTRADA in my term paper.

If we could help with something, you can contact me. 

Sincerely,

Vinicios Barretos
ACME! Cybersecurity Research

**Comment by mwullink** [comment]
Hi Vinicios,

Great that you found the problem!

> 
> 
> The timeout that occurs when ENTRADA try to connect with HDFS is caused by a change at src/main/resources/application.properties file in v2.0.21. Previous versions used impala.ssl=0, and after v2.0.21 it has changed to impala.ssl=1, causing issues for who aren't using SSL. You can see that here.

we must have made ssl=1 the default some while back, i totaly forgot about hat.

> 
> Now, about the connection timeout when run SQL ALTER TABLE, after I activate HDFS High Availability, changed SSL settings and follow steps described in your last comment, everything worked perfectly. The only thing I had to do is change ENTRADA_LOCATION_OUTPUT address, putting nameservice instead hdfs hostname.
> 
> I made a pull request changing impala.ssl back to 0 original value. Maybe someone can have trouble with this. If you think it is trivial, I suggest to change default value in ENTRADA Website.
> 

i think we might change the default value back to ssl=0
that might not be the logical choice as most new users will probably start without ssl enabled.


> Thanks for your help, ENTRADA have been a very good tool for us at Brasil. I'm in my last year of Bachelor of Computer Science and I'll cite ENTRADA in my term paper.

glad to hear that entrada is helpful for you and thatnk you for your feedback and pull request.

> 
> If we could help with something, you can contact me.

will do.


Best,

Maarten
