### ISSUE TITLE
HDFS Filesystem closed exception

### ISSUE THREAD

**Issue by mwullink** [SIDN/entrada#148]
problem:

Because the HDFS Filesystem is shared between threads (singleton), thread X can close connection used by thread Y.

fix:

Change the scope of the HDFS bean from default singleton to SCOPE_PROTOTYPE
then the spring container will give each thread their own instance of the class

java.io.IOException: Filesystem closed
        at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:472) ~[hadoop-hdfs-client-3.1.1.jar!/:na]
        at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1652) ~[hadoop-hdfs-client-3.1.1.jar!/:na]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1579) ~[hadoop-hdfs-client-3.1.1.jar!/:na]
        at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1576) ~[hadoop-hdfs-client-3.1.1.jar!/:na]
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[hadoop-common-3.1.1.jar!/:na]
        at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1591) ~[hadoop-hdfs-client-3.1.1.jar!/:na]
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1734) ~[hadoop-common-3.1.1.jar!/:na]
        at nl.sidnlabs.entrada.file.HDFSFileManagerImpl.delete(HDFSFileManagerImpl.java:270) ~[classes!/:2.1.8]
        at nl.sidnlabs.entrada.engine.AbstractQueryEngine.deleteFiles(AbstractQueryEngine.java:158) [classes!/:2.1.8]
        at nl.sidnlabs.entrada.engine.AbstractQueryEngine.compact(AbstractQueryEngine.java:102) [classes!/:2.1.8]
        at nl.sidnlabs.entrada.ScheduledCompaction.compact(ScheduledCompaction.java:105) [classes!/:2.1.8]
        at nl.sidnlabs.entrada.ScheduledCompaction.run(ScheduledCompaction.java:80) [classes!/:2.1.8]

**Comment by mwullink** [comment]
decided to not use SCOPE_PROTOTYPE but to use a ThreadLocal so bind HDFS obj to thread so it can be used from anywhere by the thread
