### ISSUE TITLE
Handle ArrayIndexOutOfBoundsException in pcap loader

### ISSUE THREAD

**Issue by mwullink** [SIDN/entrada#17]
2016-09-29 09:59:26,256-PCAPLoader-Thread-1--ERROR-nl.sidn.pcap.PcapReader:PCAP decode error:
java.lang.ArrayIndexOutOfBoundsException
       at nl.sidn.pcap.PcapReaderUtil.convertShort(PcapReaderUtil.java:57)
       at nl.sidn.pcap.decoder.TCPDecoder.decode(TCPDecoder.java:34)
       at nl.sidn.pcap.decoder.TCPDecoder.reassemble(TCPDecoder.java:83)
       at nl.sidn.pcap.PcapReader.nextPacket(PcapReader.java:250)
       at nl.sidn.pcap.PcapReader.access$0(PcapReader.java:174)
       at nl.sidn.pcap.PcapReader$PacketIterator.fetchNext(PcapReader.java:415)
       at nl.sidn.pcap.PcapReader$PacketIterator.hasNext(PcapReader.java:426)
       at nl.sidn.pcap.load.LoaderThread.read(LoaderThread.java:214)
       at nl.sidn.pcap.load.LoaderThread.doWork(LoaderThread.java:133)
       at nl.sidn.pcap.support.AbstractStoppableThread.run(AbstractStoppableThread.java:36)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)

**Comment by mwullink** [comment]
Added fix in: #604f341009d334d866c1b10d401e1af2475bd671

**Comment by mwullink** [comment]
closing issue
