### ISSUE TITLE
Error while loading data: org.apache.avro.AvroRuntimeException: Field id type:INT pos:0 not set and has no default value

### ISSUE THREAD

**Issue by gryphius** [SIDN/entrada#54]
apparently we broke something in 8dfe9ccd12628bcf68bb05aff6a9b9b2a1884e3d

if the condition ```if(respTransport != null && respMessage != null){``` 
is not met then the query id is not set at all

``` 
2017-08-11 12:56:40,872-main--INFO -nl.sidn.pcap.Main:arg 0 = switch.corrupt
2017-08-11 12:56:40,873-main--INFO -nl.sidn.pcap.Main:arg 1 = /Users/schacher/gitspace/entrada/pcap-to-parquet/target/classes/test-settings.properties
2017-08-11 12:56:40,873-main--INFO -nl.sidn.pcap.Main:arg 2 = /Users/schacher/sidn/development/tmp/pcap/input
2017-08-11 12:56:40,873-main--INFO -nl.sidn.pcap.Main:arg 3 = /Users/schacher/sidn/development/tmp/pcap/parquet
2017-08-11 12:56:40,873-main--INFO -nl.sidn.pcap.Main:arg 4 = /Users/schacher/sidn/development/tmp
2017-08-11 12:56:40,878-main--INFO -nl.sidn.pcap.util.Settings:************** entrada-setting.properties ******************
2017-08-11 12:56:40,878-main--INFO -nl.sidn.pcap.util.Settings:graphite.host: entrada-mon.sidnlabs.nl
2017-08-11 12:56:40,878-main--INFO -nl.sidn.pcap.util.Settings:output.max.packets: 3000000
2017-08-11 12:56:40,878-main--INFO -nl.sidn.pcap.util.Settings:cache.timeout.tcp.flows: 1
2017-08-11 12:56:40,878-main--INFO -nl.sidn.pcap.util.Settings:graphite.threshhold: 200
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:tld.suffix: 
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:graphite.port: 2003
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:cache.timeout: 1
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:resolver.list.google: https://developers.google.com/speed/public-dns/faq
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:graphite.prefix: test.entrada
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:cache.timeout.ip.fragmented: 1
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:graphite.connect.timeout: 3
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:buffer.pcap.reader: 65536
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:resolver.list.opendns: https://www.opendns.com/data-center-locations/
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:graphite.retention: 10
2017-08-11 12:56:40,879-main--INFO -nl.sidn.pcap.util.Settings:*************************************************************
2017-08-11 12:56:40,880-main--INFO -nl.sidn.pcap.util.FileUtil:Scan for pcap files in: /Users/schacher/sidn/development/tmp/pcap/input/switch.corrupt
2017-08-11 12:56:40,895-main--INFO -nl.sidn.pcap.Controller:Start LoaderThread
2017-08-11 12:56:40,922-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Scan for pcap files in: /Users/schacher/sidn/development/tmp/pcap/input/switch.corrupt
2017-08-11 12:56:40,922-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Found file: /Users/schacher/sidn/development/tmp/pcap/input/switch.corrupt/lako.switch.ch.20170731.015500.000009.pcap.gz
2017-08-11 12:56:40,922-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Found file: /Users/schacher/sidn/development/tmp/pcap/input/switch.corrupt/lako.switch.ch.20170731.020000.002041.pcap.gz
2017-08-11 12:56:40,922-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Found file: /Users/schacher/sidn/development/tmp/pcap/input/switch.corrupt/lako.switch.ch.20170731.020500.003359.pcap.gz
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.stats.PersistenceManager:Loaded statistics cache 66 metrics
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:------------- Loader state stats ------------------
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Loaded TCP state 6 TCP flows
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Loaded Datagram state 0 Datagrams
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Loaded Request cache 698 DNS requests
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:----------------------------------------------------
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Start loading queue from file:/Users/schacher/sidn/development/tmp/pcap/input/switch.corrupt/lako.switch.ch.20170731.015500.000009.pcap.gz
2017-08-11 12:56:41,057-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Load data for server: switch.corrupt
2017-08-11 12:56:41,065-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Start reading packet queue
2017-08-11 12:56:41,076-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:Create new Parquet write with path: /Users/schacher/sidn/development/tmp/pcap/parquet/switch_corrupt/dnsdata
2017-08-11 12:56:41,322-main--WARN -org.apache.hadoop.util.NativeCodeLoader:Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-08-11 12:56:41,993-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:Create new Parquet write with path: /Users/schacher/sidn/development/tmp/pcap/parquet/switch_corrupt/icmpdata
2017-08-11 12:56:42,444-main--INFO -org.apache.hadoop.io.compress.CodecPool:Got brand-new compressor [.snappy]
2017-08-11 12:56:42,540-main--INFO -org.kitesdk.data.spi.filesystem.FileSystemWriter:Opened output appender ParquetAppender{path=file:/Users/schacher/sidn/development/tmp/pcap/parquet/switch_corrupt/dnsdata/year=2017/month=07/day=31/server=switch.corrupt/.91d305bb-7d05-4bcd-a41d-7eae0dfd720c.parquet.tmp, schema={"type":"record","name":"dnsdata","namespace":"nl.sidn.idnp.data.dns","doc":"DNS query / response","fields":[{"name":"id","type":"int"},{"name":"unixtime","type":"long"},{"name":"time","type":"long"},{"name":"qname","type":["null","string"],"default":null},{"name":"domainname","type":["null","string"],"default":null},{"name":"len","type":["null","int"],"default":null},{"name":"frag","type":["null","int"],"default":null},{"name":"ttl","type":["null","int"],"default":null},{"name":"ipv","type":"int"},{"name":"prot","type":"int"},{"name":"src","type":"string"},{"name":"srcp","type":["null","int"],"default":null},{"name":"dst","type":"string"},{"name":"dstp","type":"int"},{"name":"udp_sum","type":["null","int"],"default":null},{"name":"dns_len","type":["null","int"],"default":null},{"name":"aa","type":["null","boolean"],"default":null},{"name":"tc","type":["null","boolean"],"default":null},{"name":"rd","type":"boolean"},{"name":"ra","type":["null","boolean"],"default":null},{"name":"z","type":"boolean"},{"name":"ad","type":["null","boolean"],"default":null},{"name":"cd","type":"boolean"},{"name":"ancount","type":["null","int"],"default":null},{"name":"arcount","type":["null","int"],"default":null},{"name":"nscount","type":["null","int"],"default":null},{"name":"qdcount","type":"int"},{"name":"opcode","type":"int"},{"name":"rcode","type":"int"},{"name":"qtype","type":["null","int"],"default":null},{"name":"qclass","type":["null","int"],"default":null},{"name":"country","type":["null","string"],"default":null},{"name":"asn","type":["null","string"],"default":null},{"name":"edns_udp","type":["null","int"],"default":null},{"name":"edns_version","type":["null","int"],"default":null},{"name":"edns_do","type":["null","boolean"],"default":null},{"name":"edns_ping","type":["null","boolean"],"default":null},{"name":"edns_nsid","type":["null","string"],"default":null},{"name":"edns_dnssec_dau","type":["null","string"],"default":null},{"name":"edns_dnssec_dhu","type":["null","string"],"default":null},{"name":"edns_dnssec_n3u","type":["null","string"],"default":null},{"name":"edns_client_subnet","type":["null","string"],"default":null},{"name":"edns_other","type":["null","string"],"default":null},{"name":"edns_client_subnet_asn","type":["null","string"],"default":null},{"name":"edns_client_subnet_country","type":["null","string"],"default":null},{"name":"labels","type":"int"},{"name":"res_len","type":"int","default":0},{"name":"svr","type":"string"},{"name":"time_micro","type":"long"},{"name":"resp_frag","type":["null","int"],"default":null},{"name":"proc_time","type":["null","int"],"default":null},{"name":"is_google","type":"boolean","default":false},{"name":"is_opendns","type":"boolean","default":false},{"name":"dns_res_len","type":["null","int"],"default":null},{"name":"server_location","type":["null","string"],"default":null},{"name":"edns_padding","type":"int","default":-1},{"name":"pcap_file","type":["null","string"],"default":null},{"name":"edns_keytag_count","type":["null","int"],"default":null},{"name":"edns_keytag_list","type":["null","string"],"default":null},{"name":"q_tc","type":["null","boolean"],"default":null},{"name":"q_ra","type":["null","boolean"],"default":null},{"name":"q_ad","type":["null","boolean"],"default":null},{"name":"q_rcode","type":["null","int"],"default":null}]}, fileSystem=org.apache.hadoop.fs.LocalFileSystem@12cd9150, avroParquetWriter=parquet.avro.AvroParquetWriter@114a85c2} for file:/Users/schacher/sidn/development/tmp/pcap/parquet/switch_corrupt/dnsdata/year=2017/month=07/day=31/server=switch.corrupt/91d305bb-7d05-4bcd-a41d-7eae0dfd720c.parquet
2017-08-11 12:56:43,794-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Read 100000 packets
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2017-08-11 12:56:45,151-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Read 200000 packets
2017-08-11 12:56:46,973-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Read 300000 packets
2017-08-11 12:56:47,469-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:---------- AbstractParquetPacketWriter Parquet writer status --------------------
2017-08-11 12:56:47,469-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:100000 packets written to parquet file.
2017-08-11 12:56:47,470-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:-----------------------------------------------------
2017-08-11 12:56:48,111-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Read 400000 packets
2017-08-11 12:56:49,782-PCAPLoader-Thread-1--WARN -nl.sidn.pcap.PcapReader:Still 6 flows queued. Missing packets to finish assembly?
2017-08-11 12:56:49,782-PCAPLoader-Thread-1--WARN -nl.sidn.pcap.PcapReader:Packets processed: 464946
2017-08-11 12:56:49,782-PCAPLoader-Thread-1--WARN -nl.sidn.pcap.PcapReader:Messages decoded:  464946
2017-08-11 12:56:49,782-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Processing time: 8717ms
2017-08-11 12:56:49,784-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.PcapReader:------------- Cache purge stats --------------
2017-08-11 12:56:49,784-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.PcapReader:TCP flow cache size: 6
2017-08-11 12:56:49,784-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.PcapReader:IP datagram cache size: 0
2017-08-11 12:56:49,784-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.PcapReader:Expired (to be removed) TCP flows: 6
2017-08-11 12:56:49,784-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.PcapReader:Expired (to be removed) IP datagrams: 0
2017-08-11 12:56:49,784-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.PcapReader:----------------------------------------------------
2017-08-11 12:56:49,785-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Marked 1609 expired queries from request cache to output file with rcode no response
2017-08-11 12:56:49,785-PCAPLoader-Thread-1--INFO -nl.sidn.pcap.load.LoaderThread:Wait until the shared queue is empty before processing the next file
2017-08-11 12:56:50,600-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:---------- AbstractParquetPacketWriter Parquet writer status --------------------
2017-08-11 12:56:50,600-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:200000 packets written to parquet file.
2017-08-11 12:56:50,600-main--INFO -nl.sidn.pcap.parquet.AbstractParquetPacketWriter:-----------------------------------------------------
2017-08-11 12:56:51,257-main--ERROR-nl.sidn.pcap.Main:Error while loading data:
org.apache.avro.AvroRuntimeException: Field id type:INT pos:0 not set and has no default value
	at org.apache.avro.generic.GenericData.getDefaultValue(GenericData.java:877)
	at org.apache.avro.data.RecordBuilderBase.defaultValue(RecordBuilderBase.java:135)
	at org.apache.avro.generic.GenericRecordBuilder.getWithDefault(GenericRecordBuilder.java:232)
	at org.apache.avro.generic.GenericRecordBuilder.build(GenericRecordBuilder.java:209)
	at nl.sidn.pcap.parquet.DNSParquetPacketWriter.write(DNSParquetPacketWriter.java:298)
	at nl.sidn.pcap.Controller.writeDns(Controller.java:156)
	at nl.sidn.pcap.Controller.start(Controller.java:109)
	at nl.sidn.pcap.Main.run(Main.java:66)
	at nl.sidn.pcap.MainTest.testRun(MainTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
````

**Comment by mwullink** [comment]
Fixded
